[package]
name = "yp-tic-tak-toe"
version = "0.1.0"
authors = ["yp.pan <pan.yiping.fi@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "yp-tic-tak-toe"
path = "main.rs"
